export const CITY = [{ value: "시" }, { value: "서울특별시" }];

export const SEOUL = [
  { value: "구" },
  { value: "강남구" },
  { value: "강동구" },
  { value: "강북구" },
  { value: "강서구" },
  { value: "관악구" },
  { value: "광진구" },
  { value: "구로구" },
  { value: "금천구" },
  { value: "노원구" },
  { value: "도봉구" },
  { value: "동대문구" },
  { value: "동작구" },
  { value: "마포구" },
  { value: "서대문구" },
  { value: "서초구" },
  { value: "성동구" },
  { value: "성북구" },
  { value: "송파구" },
  { value: "양천구" },
  { value: "영등포구" },
  { value: "용산구" },
  { value: "은평구" },
  { value: "종로구" },
  { value: "중구" },
  { value: "중랑구" },
];

export const SYMPTOM = [
  { value: "증상" },
  { value: "의식장애" },
  { value: "수족마비" },
  { value: "뇌경색" },
  { value: "심근경색" },
  { value: "복부창상" },
  { value: "손가락절단" },
  { value: "개에게물림" },
  { value: "신체절단" },
  { value: "위경련" },
  { value: "혈액투석" },
  { value: "신장투석" },
  { value: "조산" },
  { value: "과호흡" },
  { value: "열성경련" },
  { value: "소아구토" },
  { value: "화상" },
];
