export const city = [{ value: "시를 골라주세요" }, { value: "서울특별시" }];

export const seoul = [
  { value: "구를 골라주세요" },
  { value: "강남구" },
  { value: "강동구" },
  { value: "강북구" },
  { value: "강서구" },
  { value: "관악구" },
  { value: "광진구" },
  { value: "구로구" },
  { value: "금천구" },
  { value: "노원구" },
  { value: "도봉구" },
  { value: "동대문구" },
  { value: "동작구" },
  { value: "마포구" },
  { value: "서대문구" },
  { value: "서초구" },
  { value: "성동구" },
  { value: "성북구" },
  { value: "송파구" },
  { value: "양천구" },
  { value: "영등포구" },
  { value: "용산구" },
  { value: "은평구" },
  { value: "종로구" },
  { value: "중구" },
  { value: "중랑구" },
];

export const Symptom = [
  { value: "증상을 골라주세요" },
  { value: "수족 마비" },
  { value: "의식장애" },
  { value: "뇌경색" },  
  { value: "심근경색" },  
  { value: "복부 내/외상" },  
  { value: "손가락절단" },      
  { value: "개에게물림" }, 
  { value: "신체절단" },
  { value: "응급내시경" }, 
  { value: "혈액투석" },
  { value: "신장투석" },  
  { value: "조산" },  
  { value: "과호흡" },  
  { value: "소아 머리손상"},
  { value: "열성 경련" },
  { value: "소아 알레르기" },
  { value: "화상" }
];
